version: '2.1'
services:
    redis:
        image: redis

    db:
        image: mariadb:10.3
        environment:
          - MYSQL_ROOT_PASSWORD
        ports:
          - 3306
    base:
        build:
            context: ./docker/app
            args:
                - XDEBUG
        working_dir: /var/www/app
        volumes:
            - ./:/var/www/app:rw
            - ./docker/app/app.ini:/usr/local/etc/php/conf.d/app.ini:ro
            - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

    app:
        extends: base
        restart: unless-stopped
        depends_on:
          - redis
          - db
        links:
            - redis
            - db

    app_cli:
        extends: base
        depends_on:
        - redis
        - db
        links:
            - redis
            - db

    web:
        image: nginx:1.15
        restart: unless-stopped
        ports:
            - 8081:80
        links:
            - app
        volumes:
          - ./docker/web/app.conf:/etc/nginx/conf.d/default.conf:ro
        volumes_from:
            - app